version: "3.5"

networks:
  net:

services:

  bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    restart: always
    env_file: ".env"
    environment:
      - "PORT=80"
      - "ENV_RUNTIME=docker"
    command:
      - "./bot"
    networks:
      - net

  bot_redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6381:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - type: bind
        source: "${STORAGE_RD_DIR}"
        target: "/data"
    networks:
      - net
